---
title: Exploring Further with Marissa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fornaromarissa@gmail.com
url: https://exploringfurther.com
author: Marissa Fornaro
plugins:
- jekyll-seo-tag
