title: Exploring Further with Marissa
email: fornaromarissa@gmail.com
url: "https://exploringfurther.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Marissa Fornaro

plugins:
  - jekyll-seo-tag
